android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g
android.lint.worker.heapSize=1024m
# Fix for INSTALL_BASELINE_PROFILE_FAILED
android.baselineprofile.enable=false

# Release Signing Properties
# Replace these with your actual keystore values
RELEASE_STORE_PASSWORD=SealYoutube
RELEASE_KEY_ALIAS=sealyoutube
RELEASE_KEY_PASSWORD=SealYoutube
